export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERROR_LOADING_INGREDIENTS = 'ERROR_LOADING_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const RESET_ORDERS = 'RESET_ORDERS';


export const AUTH_AUTO_CHECK = 'AUTH_AUTO_CHECK';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE = 'AUTH_INITIATE';
export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCEDED = 'LOGOUT_SUCCEDED';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';





